import { Router } from "express";
import { requireAuth } from "../../middlewares/auth";
import authRouter from "./auth";
import prospectsRouter from "./prospects";
import pipelineRouter from "./pipeline";
import sequencesRouter from "./sequences";
import signalsRouter from "./signals";
import dashboardRouter from "./dashboard";
import activitiesRouter from "./activities";
import workflowsRouter from "./workflows-api";
import templatesRouter from "./templates-api";
import webhooksRouter from "./webhooks-api";
import accountsRouter from "./accounts";
import emailRouter from "./email";
import searchRouter from "./search";
import usersRouter from "./users";
import teamRouter from "./team";
import apiKeysRouter from "./api-keys";
import analyticsRouter from "./analytics";
import pluginsRouter from "./plugins";
import memoryRouter from "./memory";
import meetingsRouter from "./meetings";
import aiSdrRouter from "./plugins/ai-sdr";
import dealCoachRouter from "./plugins/deal-coach";
import revenueRouter from "./plugins/revenue";
import knowledgeRouter from "./plugins/knowledge";
import executiveRouter from "./plugins/executive";
import sourcingRouter from "./sourcing";
import notificationsRouter from "./notifications";
import adminRouter from "./admin";
import pluginMarketplaceRouter from "./plugin-marketplace";
import auditRouter from "./audit";
import enrichmentRouter from "./plugins/enrichment";
import ereputationRouter from "./plugins/ereputation";
import tasksRouter from "./tasks";
import reportingRouter from "./reporting";
import collaborationRouter from "./collaboration";
import complianceRouter from "./compliance";
import ssoRouter from "./sso";
import apiDocsRouter from "./api-docs";
import billingRouter from "./billing";
import integrationsRouter from "./integrations";
import publicApiRouter from "./public-api";

const router = Router();

router.use("/auth", authRouter);
router.use("/prospects", requireAuth, prospectsRouter);
router.use("/pipeline", requireAuth, pipelineRouter);
router.use("/sequences", requireAuth, sequencesRouter);
router.use("/signals", requireAuth, signalsRouter);
router.use("/dashboard", requireAuth, dashboardRouter);
router.use("/activities", requireAuth, activitiesRouter);
router.use("/workflows", requireAuth, workflowsRouter);
router.use("/templates", requireAuth, templatesRouter);
router.use("/webhooks", requireAuth, webhooksRouter);
router.use("/accounts", requireAuth, accountsRouter);
router.use("/email", requireAuth, emailRouter);
router.use("/search", requireAuth, searchRouter);
router.use("/users", requireAuth, usersRouter);
router.use("/team", requireAuth, teamRouter);
router.use("/api-keys", requireAuth, apiKeysRouter);
router.use("/analytics", requireAuth, analyticsRouter);
router.use("/plugins", pluginsRouter);
router.use("/memory", memoryRouter);
router.use("/meetings", meetingsRouter);
router.use("/ai-sdr", aiSdrRouter);
router.use("/deal-coach", dealCoachRouter);
router.use("/revenue", revenueRouter);
router.use("/knowledge", knowledgeRouter);
router.use("/executive", executiveRouter);
router.use("/sourcing", sourcingRouter);
router.use("/notifications", notificationsRouter);
router.use("/admin", adminRouter);
router.use("/plugin-marketplace", pluginMarketplaceRouter);
router.use("/audit", auditRouter);
router.use("/enrich", enrichmentRouter);
router.use("/ereputation", requireAuth, ereputationRouter);
router.use("/tasks", requireAuth, tasksRouter);
router.use("/reporting", requireAuth, reportingRouter);
router.use("/collaboration", requireAuth, collaborationRouter);
router.use("/compliance", requireAuth, complianceRouter);
router.use("/sso", requireAuth, ssoRouter);
router.use("/api-docs", apiDocsRouter);
router.use("/billing", billingRouter);
router.use("/integrations", integrationsRouter);
router.use("/public", publicApiRouter);

export default router;
